package org.apache.cayenne.tutorial.persistent.auto;

import org.apache.cayenne.exp.Property;
import org.apache.cayenne.tutorial.persistent.Auditable;
import org.apache.cayenne.tutorial.persistent.Painting;

import java.util.Date;
import java.util.List;

/**
 * Class _Artist was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Artist extends Auditable {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<Date> CREATION_DATE2 = new Property<Date>("creationDate2");
    public static final Property<Date> DATE_OF_BIRTH = new Property<Date>("dateOfBirth");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<List<Painting>> PAINTINGS = new Property<List<Painting>>("paintings");

    public void setCreationDate2(Date creationDate2) {
        writeProperty("creationDate2", creationDate2);
    }
    public Date getCreationDate2() {
        return (Date)readProperty("creationDate2");
    }

    public void setDateOfBirth(Date dateOfBirth) {
        writeProperty("dateOfBirth", dateOfBirth);
    }
    public Date getDateOfBirth() {
        return (Date)readProperty("dateOfBirth");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToPaintings(Painting obj) {
        addToManyTarget("paintings", obj, true);
    }
    public void removeFromPaintings(Painting obj) {
        removeToManyTarget("paintings", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Painting> getPaintings() {
        return (List<Painting>)readProperty("paintings");
    }


}
